services:
  minecraft:
    build:
      context: .
    env_file: .env
    restart: unless-stopped
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${RCON_PORT}:${RCON_PORT}
    volumes:
      - ./data:/server
